### ISSUE TITLE
Changes to the database schema.

### ISSUE THREAD

**Issue by ducphanduyagentp** [s-newman/skitter#85]
I think it is best to get as little information as possible from the user input at the signup process.

- Since a user may log in but not finish the signup process, a session is still established but it is not guaranteed that the user information will be inserted into the database. I suggest the following changes:

  - Add a default value of `0` and empty string to the `user_id` and `username` so that we can keep track of users that are logged in but not signed up.
  - The RIT username is unique by nature so I suggest making it the primary key as well. We can then make a session table with a foreign key to the `rit_username`

- To reduce the amount of information being processed by Java at signup, we can make a default profile picture and let the user change it later.
- The email can default to the RIT email for simplicity.

With the changes above, a user will only be required to submit a username. Other information can be derived from the RIT username and taken from the RIT LDAP server.

Let me know what you think @s-newman.

**Comment by s-newman** [comment]
A few comments:
- If a user does not finish the signup process, we shouldn't store their information in the database.  The session ID may persist, but since they ever actually submitted the signup form we shouldn't store anything in the database.
  - Using `rit_username` as the primary key sounds good to me, then we can drop `user_id` from the table altogether.  I think `username` should still be `NOT NULL`, because there's not really any point in keeping login data for users that haven't been created.
- Using a default profile picture sounds good, there's one already existing at `frontend/app/ui/static/img/default-profile.png` that we can use.
- Yep, that works (and makes more sense).
I can make the changes to `new-account.html` - it'll be a pretty simple page now.
